version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: 
      timeout: 300
      runas: root
  ApplicationStop:
    - location: 
      timeout: 300
      runas: root
