name: Deploy

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
jobs:
  build:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps: 
    - uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: codedeploy
      run: aws deploy create-deployment --application-name amazonygithub --deployment-group-name grupoamazonygithub --github-location repository=${{ github.repository }},commitId=${{ github.sha }}